Add "ruby-vips" because CI fails
Run bin/rails db:test:prepare test:system
bin/rails aborted!
LoadError: ImageProcessing::Vips requires the ruby-vips gem. Please add `gem "ruby-vips", "~> 2.0"` to your Gemfile. (LoadError)